### ISSUE TITLE
WiFi doesn't work on Variscite DART-6UL

### ISSUE THREAD

**Issue by KemperVreden** [balena-os/balena-os#292]
Variscite DART-6UL successfully boots resinOS. Both Ethernet-Ports are being recognized by the System. However WiFi does not work. Here's what's inside the console:

```
[   13.831384] brcmfmac: brcmf_sdio_drivestrengthinit: No SDIO Drive strength init done for chip 43430 rev 1 pmurev 24
[   13.968427] usbcore: registered new interface driver brcmfmac
[   14.022452] brcmfmac mmc0:0001:1: Direct firmware load for brcm/brcmfmac43430-sdio.bin failed with error -2
[   14.180557] brcmfmac mmc0:0001:1: Falling back to user helper
[   15.353737] cfg80211: World regulatory domain updated:
[   15.357618] cfg80211:  DFS Master region: unset
[   15.380732] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
[   15.389245] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
[   15.408156] cfg80211:   (2457000 KHz - 2482000 KHz @ 40000 KHz), (N/A, 2000 mBm), (N/A)
[   15.421330] cfg80211:   (2474000 KHz - 2494000 KHz @ 20000 KHz), (N/A, 2000 mBm), (N/A)
[   15.428081] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (N/A)
[   15.458118] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2000 mBm), (0 s)
[   15.467263] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2000 mBm), (0 s)
[   15.478399] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 2000 mBm), (N/A)
[   15.485998] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 0 mBm), (N/A)
[   15.661281] FAT-fs (mmcblk1p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[   16.340689] brcmfmac: brcmf_sdio_htclk: HT Avail timeout (1000000): clkctl 0x50
[   17.366787] brcmfmac: brcmf_sdio_htclk: HT Avail timeout (1000000): clkctl 0x50
```

Hope this helps fixing it since this board is such a nice and professional / industrial-ready device!

**Comment by floion** [comment]
Hi @KemperVreden , at this point we don't have this as a priority but as soon as the time allows it, we shall look into this.
Have you made any progress on your side?

**Comment by dpruessner** [comment]
I'm encountering this too-- DART-6UL-Y2-xx-WB.

I notice that the driver initializes the first time on the DART-6UL EVK (maybe some u-boot specific code turns on certain GPIOs when it interrogates the EVK's I2C flash memory identifier or something).

I can eventually get it working on my application board by loading `brcmfmac` module, then removing it, then re-loading it.  Second time seems to take.  But this seems like a **very sketchy** solution for us to go to production with.

Any resolution/help would be appreciated.

**Comment by agherzan** [comment]
From the logs @KemperVreden provided it seems it misses "brcmfmac43430" firmware. Are you using an external dongle?

@dpruessner I a little puzzled why is it working for you, even with that hack. Did you manually add the firmware?

**Comment by dpruessner** [comment]
I'm running our own Buildroot base linux image. 

I downloaded the Variscite Debian image from wget ftp://ftp.variscite.com/DART-6UL/Software/mx6ul-dart-debian-recovery-sd.v20.img.gz .  With the SD card's kernel image, I loaded the `zImage` and the `imx6ull-var-dart-nand_wifi.dtb` onto the NAND flash; copied the /lib/firmware/b* directories over onto our image, and the /lib/modules/4.1.15-224502-gcf... modules over to our image.  

In other words: the setup I was testing was with the March, 2017 Variscite Debian kernel image, modules, device tree, and firmware binaries, with a buildroot linux base.

Is there a better recommended kernel version commit # for 4.1.x with the WiFi working better than commit cf341517 ?

Since I last posted, I rebuilt the kernel (using `git checkout cf341517` in the Variscite kernel repository) on our end to include drivers we need for our application.  It seems better behaved with the following messages:

```
brcmfmac: brcmf_sdio_drivestrengthinit: No SDIO Drive strength init done for chip 43430 rev 1 pmurev 24
brcmfmac: brcmf_sdio_htclk: HT Avail timeout (1000000): clkctl 0x50
brcmfmac: brcmf_sdio_htclk: HT Avail timeout (1000000): clkctl 0x50
brcmfmac: brcmf_sdio_drivestrengthinit: No SDIO Drive strength init done for chip 43430 rev 1 pmurev 24
brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Nov 14 2016 00:32:49 version 7.45.41.32 (r662793) FWID 01-8b473c3f
```

Same HT Avail timeout problem, but it displays the firmware version that it actually loads.  Funny thing is that we did not change the binary firmware files' location or contents.

**Comment by agherzan** [comment]
@floion did we test resinOS WiFi support on DART board?

**Comment by floion** [comment]
At this point wifi is not functional on our OS. As I said, that is not high up on our priority list, @agherzan

**Comment by floion** [comment]
Hi @dpruessner how did you get to download the image from Variscite's ftp? It requires a login now. Did it always require that?

**Comment by floion** [comment]
Tested a staging OS release (version 2.29.2+rev2) on the official Variscite carrier board + SoM (https://www.variscite.com/products/evaluation-kits/dart-6ul-kits/) and WiFi is working.
So next OS release (2.30.0 or newer will contain the changes that make WiFi functional)
